config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'math' => 'math#mhome'
  get 'science' => 'science#shome'
  get 'algebra' => 'math#algebra'
  get 'geometry' => 'math#geometry'
  get 'trigonometry' => 'math#trigonometry'
  get 'calculus' => 'math#calculus'
  get 'differentialequations' => 'math#differentialequations'
  get 'matrixmethodslinearalgebra' =>'math#matrixmethodslinearalgebra'
  get 'numericalanalysis' => 'math#numericalanalysis'
  get 'complexvariables' => 'math#complexvariables'
  get 'fourieranalysis' => 'math#fourieranalysis'
  get 'generalphysics' => 'science#generalphysics'
  get 'astronomy' => 'science#astronomy'
  get 'electromagnetism' => 'science#electromagnetism'
  get 'mechanicsdynamicslagrangianhamiltonian' => 'science#mechanicsdynamicslagrangianhamiltonian'
  get 'quantummechanics' => 'science#quantummechanics'
  get 'thermodynamicsstatisticalmechanics' => 'science#thermodynamicsstatisticalmechanics'
  get 'nuclearparticlephysics' => 'science#nuclearparticlephysics'
  get 'astrophysics' => 'science#astrophysics'
  get 'relativity' => 'science#relativity'
  get 'fluiddynamics' => 'science#fluiddynamics'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end
def application
end

app/controllers/math_controller.rb
class MathController < ApplicationController
    def mhome
    end
    def algebra
    end
    def geometry
    end
    def trigonometry
    end
    def calculus
    end
    def differentialequations
    end
    def matrixmethodslinearalgebra
    end
    def numericalanalysis
    end
    def complexvariables
    end
    def fourieranalysis
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def contact
  end
  def about
  end
end

app/controllers/science_controller.rb
class ScienceController < ApplicationController
    def shome
    end
    def generalphysics
    end
    def astronomy
    end
    def electromagnetism
    end
    def mechanicsdynamicslagrangianhamiltonian
    end
    def quantummechanics
    end
    def thermodynamicsstatisticalmechanics
    end
    def nuclearparticlephysics
    end
    def astrophysics
    end
    def relativity
    end
    def fluiddynamics
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Math and Science"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{page_title} | #{base_title}"                 # String interpolation
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div>
  <small>
    <p>   The <a href=https://math-and-science.herokuapp.com/>Math and Science Page</a> created by Christian Kelley</p>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Math", math_path %></li>
      <li><%= link_to "Science", science_path %></li>
      <li><a href=https://math-and-science-blogger.herokuapp.com/>Blogger</a></li>
      <li> <%= link_to "About",   about_path %>  </li>
      <li> <%= link_to "Contact", contact_path %>  </li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Math and Science Home", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Math", math_path %></li>
            <li><%= link_to "Science", science_path %></li>
            <li><a href=https://math-and-science-blogger.herokuapp.com/>Blogger</a></li>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/math/algebra.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>MATH: ALGEBRA</b></h1>
     </div>
     <h2><p>Algebra is the most logical starting point for someone wanting to learn mathematics.  The concepts of numbers,
     counting, addition and subtraction, as well as multiplication and division are fundamental algebraic concepts.  Even more
     importantly, developing a solid foundation in the techniques and application of elementary algebra are essential because
     subsequent higher-level mathematics are structures built upon the foundation which is algebra.</p></h2>
  </body>    
</html>

app/views/math/calculus.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>MATH: CALCULUS</b></h1>
     </div>
     <h2><p>Calculus is the culimation of years of studying algebra, geometry, and trigonometry.  What distinguishes calculus from
     these other fields of mathematics is that calculus makes mathematics fully dynamic by studying rates of change and relating
     them to appopriate variables and functions.  However, calculus is much richer than just taking static variables and incorporating
     dynamic entites by considering their rates of change; it deals with studying function behavior and considers introduces the idea
     of a limiting process to study qualitative behavior of functions as they approach certain limits that heretofore have not been 
     considered, such as division by zero and allowing functions to extend to infinity.  It is not that division by zero is allowed 
     in calculus or that infinity takes on a defined value; but the process of thinking through what happens to functions in these 
     limits is introduced and quantified by the concepts of convergence and divergence.  These concepts are encapsulated in the study 
     of infinite sequences and series, which provide conditions that allow powerful techniques to draw definitive conclusions 
     regardding predictable function behavior that can be proven rigorously.  A standard calculus cirriculum follows sums and 
     sequences with an extension to two and then three dimensions where vector calculus is considered and the full analysis of 
     three-dimensional space becomes realized, and different coordinate systems are introduced which allow for symmetry considerations 
     to be exploited.  </p></h2>
  
  </body>    
</html>

app/views/math/differentialequations.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>MATH: DIFFERENTIAL EQUATIONS</b></h1>
     </div>
     <h2><p>Having a solid understanding of calculus and the physical meaning of differential quantities, the student is now prepared 
     to study purely dynamical systems, namely in the form of differential equations.  Most students who have completed a calculus 
     cirriculum will have glazed over the simplest form of a differential equation, namely the exponential decay formula; but the study 
     of differential equations takes on an incredibly rich formulaiton that describes physical systems purely in terms of quantities that 
     change with time and space and depend on where and when the system under consideration is taking place.  The ideas of initial and 
     boundary conditions are essential to the study of differential equations if a solution is hoped to be found; and more often than not
     closed-form analytical solutions do not exist.  One must resort to numerical techniques (numerical analysis) to approximate solutions
     to many differential equations, particularly partial differential equations.  </p></h2>
  
  </body>    
</html>

app/views/math/geometry.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>MATH: GEOMETRY</b></h1>
     </div>
     <h2><p>Geometry is often introduced as an intermediary mathematical topic to bridge the gap between introductory
     algebra and advanced algebra or trigonometry.  Initially geometry is often taught using postulates as outlined by
     Euclid and the construction of the logical proof process is emphasized.  Many students find this approach tedious and
     abstract; which, frankly, it is.  The main point to be learned from this introductory material is the logical approach
     taken to deduce conclusions from a given set of postulates.<br><br>Geometry consists of much more than just the ideas outlined 
     in Euclid's <em>Elements</em>.  Geometry is used to derive simple formulas for areas and volumes of symmetrical objects,
     but the general case is reserved for the powerful techniques introduced in calculus.  There also exists a separate field 
     of geometry known as analytical geometry which is indespensiable in the study of astrodynamics.  Finally, when calculus
     is merged with geometry the topic of differential geometry can be introduced, upon which (Einstein's) general theory of 
     relativity is constructed.</p></h2>
  </body>    
</html>

app/views/math/home.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>MATH</b></h1>
     </div>
     <div>
     <h2><p>This website is dedicated to generating and maintaining poeple's interest in mathematics and science.  
     There is something here for everyone.  Current events, research material, historical perspectives, and an 
     all-inclusive online blogging community are just some of the many features this math and science webpage
     offers.  Please peruse the website at your leisure.  Who knows, you may learn something new or gain a different
     perspective concerning math and science from what you had before coming to this site.  Enjoy!</p></h2>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
    </div>
    
  </body>    
</html>

app/views/math/matrixmethodslinearalgebra.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>MATH: MATRIX METHODS AND LINEAR ALGEBRA</b></h1>
     </div>
     <h2><p>With an understanding of differential equations and their usefulness in solving physical problems, it is customary to study 
     systems of equations to be solved simultaneously (linear algebra) and the usefulness of matrices in simplifying such systems.  The 
     usefulness of matrix methods soon becomes apparent when decompositions are realized, and the all important concepts of eigenvalues 
     and eigenvectors are introduced and begin to become understood by the student.  </p></h2>
  
  </body>    
</html>

app/views/math/mhome.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>MATH</b></h1>
     </div>
     <div>
     <h2><p>This is the mathematics home page.  Below are links to pages with information about
     some of the exciting fields of mathematics.  </p></h2>
       <ul>
           <li><%= link_to "Algebra", algebra_path %></li>
           <li><%= link_to "Geometry", geometry_path %></li>
           <li><%= link_to "Trigonometry", trigonometry_path %></li>
           <li><%= link_to "Calculus", calculus_path %></li>
           <li><%= link_to "Differential Equations", differentialequations_path %></li>
           <li><%= link_to "Matrix Methods and Linear Algebra", matrixmethodslinearalgebra_path %></li>
           <li><%= link_to "Numerical Analysis", numericalanalysis_path %></li>
           <li><%= link_to "Complex Variables", complexvariables_path %></li>
           <li><%= link_to "Fourier Analysis", fourieranalysis_path %></li>
       </ul>
       </div>
  </body>    
</html>

app/views/math/trigonometry.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>MATH: TRIGONOMETRY</b></h1>
     </div>
     <h2><p>Trigonometry, at its most fundamental level, is just the study of ratios.  However, this explanation does not do
     the field of trigonometry justice.  From these ratios we can define functions that allow us to completely characterize the 
     position of a circle (of any radius, though the 'unit' circle where the radius is equal to one is usually introduced first) 
     in terms of its direction.  This brings us to the precipice of not only vectors, but also calculus.  In fact, sometimes 
     trigonometry is referred to as 'pre-calculus'.  It is through geometry that students are often thought to think of the 
     divisions of a circle in terms of radians, as opposed to the degrees they are most familiar with.<br><br>
     Below is an image of the unit circle, and a table with the corresponding values of the trigonometric functions 
     in both radian and degree measurements.  </p></h2>
  
  <h1><%= link_to image_tag("unit circle.jpg")%></h1>
  <h1><%= link_to image_tag("trig values.jpg")%></h1>
  
  </body>    
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<h1><%= link_to image_tag("cak.jpg")%></h1><br>
<p>
  Christian Kelley is an Astrophysicist and Applied Mathematician who graduated
  from the University of Colorado at Boulder.  His desire to see more people 
  interested in math and science, both for casual and academic puproses, has led
  him to create this website.  Feel free to contact him via e-mail:<br>
  cakelley@colorado.edu
</p>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Feel free to contact the website administrator, Christian Kelley, with any 
  questions, comments, or concerns via e-mail:<br> cakelley@colorado.edu
</p>

app/views/pages/home.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1>PROMOTING INTEREST IN<br>
         <b>MATH AND SCIENCE</b></h1>
     </div>
     <div>
     <h2><p>This website is dedicated to generating and maintaining poeple's interest in mathematics and science.  
     There is something here for everyone.  Current events, research material, historical perspectives, and an 
     all-inclusive online blogging community are just some of the many features this math and science webpage
     offers.  Please peruse the website at your leisure.  Who knows, you may learn something new or gain a different
     perspective concerning math and science from what you had before coming to this site.  Enjoy!</p></h2>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
       <p><b><u>Why Math and Science?</u></b><br>
       The United States is falling behind other countries when it comes to proficiency in mathematics and 
       scientific studies.</p>
    </div>
    
  </body>    
</html>

app/views/science/astronomy.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE: ASTRONOMY</b></h1>
     </div>
     <h2><p>The science of astronomy aims to explain the universe we live in, what it is comprised of, how things came to
     be, why things are how we perceive them, and what to expect in the future.  Through observation and interpretation, along with 
     the assertion that space is homogeneous (the same processes going on now are the same as they were in the past) and isotropic 
     (there is no preference for one location over another, i.e., our galaxy is in principle not 'special' when compared to the other 
     billions of galaxies in the universe) astronomers interpret the world we live in with respect to the universe that surrounds us.  Naturally, 
     much of the emphasis in astronomy centers on the Sun, the closest star to us and the one we know the most about; our own Solar System; and our 
     own galaxy, the Milky Way.  But studies extend far beyond what we consider our own local environment, and much can and has been learned about
     stellar composition, evolution, and formation simply through observations and their subsequent interpretations.  General (i.e., introductory) 
     astronomy focuses on learning the fundamentals of our own Solar System, beginning with the Sun and the four terrestrial (or rocky) planets
     as well as the four Jovian (or gaseous) planets.  After this, studies move on to include galactic formations from a general perspective, 
     offering interpretations for the most well-known observations and introducing ideas and concepts that can be understood at a fundamental level.  
     The emphasis is on learning fundamentals rather than specific points at this juncture.</p></h2>
  </body> 
  
  <br>
  <ul><u>Astronomy Links</u>
  <li><a href=https://www.ras.org.uk/education-and-careers/for-everyone/98-general-astronomy-a-astrophysics-links>Royal Astronomical Society Astronomy Links</li>
  <li><a href=http://en.wikibooks.org/wiki/General_Astronomy/The_Early_Origins_of_Astronomy>Wiki Books Ancient Astronomies</li>
  </ul>
</html>

app/views/science/astrophysics.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE: ASTROPHYSICS</b></h1>
     </div>
     <h2><p>With a much more solid foundation in studying advanced physics for a couple of years, students now are at a point
     where they can combine their introductory astronomy studies with their physical knowledge to quantitatively study the evolution of 
     stars, galaxies, and other astrophysical phenomena.  What once seemed like coincidences early on in one's studies now seem more the 
     result of physics on the grandest of scales, such as the shapes of galaxies determined by their angular momentum and why spiral galaxies 
     are moving faster far out in the limbs than in the middle near the bulge.  But not everything is satisfactory; for each question that is answered 
     there is one that has not yet been satisfactorily solved.  These include dark matter and dark energy, a consistent model for the metallicity 
     of a given star, and why we observe systems that seem impossible from our physical models (i.e., "hot Jupiter's").  It is safe to say that the 
     field of astrophysics will have researchers continuing to seek answers to these problems for many years to come.  
     </p></h2>
  </body>
  <br>
  <ul><u>Astrophysics Links</u>
  <li><a href=http://supernova.lbl.gov/~evlinder/umass/link.html>Supernova Astrophysics Links</a></li>
  <li><a href=http://www.astrohandbook.com/links.html>Handbook for Astrophysics</a></li>
  </ul>
</html>

app/views/science/electromagnetism.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE: ELECTROMAGNETISM</b></h1>
     </div>
     <h2><p>One of the greatest triumphs in the history of science has been the synthesis of two seemingly disparate concepts, electricity
     and magnetism; into one single, coherent, and unified theory of electromagnetism or electrodynamics (when motion, including relativistic, 
     is considered).  Maxwell's Equations completely describe the electric and magnetic fields of any charge distribution under consideration, 
     and their inconsistency with Newtonian physics is what led Einstein to develop his theory of relativity (first special, meaning without 
     gravity; and then general to include gravity) and provide consistency between Maxwell's Equations and experimental observations.  There are many
     reasons why electromagnetism is introduced early in physics curriculum:  the theory is self-consistent;  it can be completely understood with 
     only limited mathematical knowledge; and the implications of how such a theory comes together into a unified and coherent structure often leaves 
     a lasting impression on students.  As such, electromagnetism and electrodynamics provide an excellent starting point for bridging the gap between 
     general and more advanced physics studies.</p></h2>
  </body>
  
  <br>
  <ul><u>Electromagnetism Links</u>
  <li><a href=http://www.gcsescience.com/pme.htm>GC Scince Electromagnetism</a></li>
  <li><a href=http://history.hyperjeff.net/electromagnetism>History of Electromagnetism</a></li>
  </ul>
</html>

app/views/science/fluiddynamics.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE: FLUID DYNAMICS</b></h1>
     </div>
     <h2><p>Fluid dynamics studies the properties and characteristics of fluids in motion.  Generally a fluid is distinguished from a 
     solid, and is typically either a gas (compressible) or a liquid (incompressible).  FLuid dynamics is a very rich and intricate field
     of study, encompassing topics such as aerodynamics, turbulence, shock waves, gravity waves, just to name a few.  It is very mathematically
     involved and aside from a few introductory concepts is typically not included in an undergraduate cirriculum.  It's importance cannot be 
     understated however; everything from the motion of an airplane in the sky to a ship in the ocean can be modeled using fluid dynamics.  
     </p></h2>
  </body>    
  <br>
  <ul><u>Relativity Links</u>
  <li><a href=http://www.livescience.com/47446-fluid-dynamics.html>Live Science Fluid Dynamics</a></li>
  <li><a href=http://www.ldeo.columbia.edu/~martins/hydro/lectures/fluid_dynamics.html>Principles of Fluid Dynamics, Columbia University</a></li>
  </ul>
</html>

app/views/science/generalphysics.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE: GENERAL PHYSICS</b></h1>
     </div>
     <h2><p>General physics introduces a new way of thinking about how the world around you works, described
     quantitatively by physical insight and qualitatively through mathematical analysis.  Though often covered in
     only an introductory manner, general physics courses cover a lot of information quickly and much of the learning 
     process is independent.  Rather than focusing on a specific area of emphasis, general physics covers many areas
     without a great deal of detail in any one particular category.  This is often a point of frustration for students 
     because they are expected to accept given formulae and results often without going through the derivation process.  
     The reason for this is that students in general physics courses are not expected to be equipped with the mathematical 
     machinery needed to prove the theorems and laws that are provided and used without derivation.  Much of the emphasis
     in general physics is learning how to think like a physicist, including the approach to problem solving and looking for 
     connections between topics that may otherwise seem unrelated.  General physics is intended to prepare students for what is to come.</p></h2>
  </body>    
  <br>
  <ul><u>General Physics Links</u>
  <li><a href=http://surendranath.tripod.com/Applets.html>General Physics Java Applets</a></li>
  <li><a href=http://www.physicsclassroom.com/>The Physics Classroom</a></li>
  </ul>
</html>

app/views/science/mechanicsdynamicslagrangianhamiltonian.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE: MECHANICS, DYNAMICS, LAGRANGIAN, HAMILTONIAN</b></h1>
     </div>
     <h2><p>General physics introduces Newtonian mechanics and dynamics; that is to say, physics
     as formulated by Isaac Newton.  However, as is often the case in physical theories, there exist more
     than one way to arrive at the same solution.  Another system of mechanics and dynamics, known as Lagrangian
     and Hamiltonian physics, are more mathematically sophisticated models of the Newtonian concepts and both
     give the same results, but the Lagrangian and Hamiltonian methods have a much wider range of applicability and 
     often turn problems which are extraordinarily difficult within the Newtonian framework into much simpler and far 
     more tractable form to be solved.  Further, when moving onto further advanced physics courses such as quantum mechanics, 
     nuclear and particle physics, general relativity, and field theories the framework as developed in the Lagrangian and 
     Hamiltonian formulation of mechanics and dynamics makes the transition much less painful inasmuch as the approach is much 
     more abstract and, oddly, therefore helpful.</p></h2>
  </body>    
  <br>
  <ul><u>Largangian and Hamiltonian Dynamics Links</u>
  <li><a href=http://www.physicsinsights.org/lagrange_1.html>Lagrange Dynamics</li>
  <li><a href=http://iopscience.iop.org/0036-0279/32/4/R04>IOP Physics Structure of Hamiltonian Mechanics</li>
  </ul>
</html>

app/views/science/nuclearparticlephysics.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE: NUCLEAR AND PARTICLE PHYSICS</b></h1>
     </div>
     <h2><p>Taking up where quantum mechanics left off, the study of nuclear and particle physics offers 
     amazing new insight into the constituents of matter.  While the electron is considered an elementary particle, 
     the proton and neutron are not; being comprised of quarks which themselves carry fractional amounts of the standard 
     electrical charge.  An exciting new world of physics is opened up when students learn about particle accelerators and 
     study experimental results from highly energetic particles which collide with one another.  Though the particle itself may 
     not exist long enough to be observed visually, there are traces left, such as resonance widths that can be measured and shown
     to be certain, identifiable particles based on the direction of movement (i.e., charged or neutral) and radius of curvature 
     (which can be used to determine momentum).  This is an exciting field of active and ongoing research.  
     </p></h2>
     <br>
     <ul><u>Nuclear and Particle Physics Links</u>
     <li><a href=http://pdg.lbl.gov/>Particle Data Group</li>
     <li><a href=http://www.rarf.riken.go.jp/rarf/np/nplab.html>Virtual Library of Nuclear Physics</a></li>
     </ul>
  </body>    
</html>

app/views/science/quantummechanics.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE: QUANTUM MECHANICS</b></h1>
     </div>
     <h2><p>Quantum mechanics marks the departure from studying things with which we are familiar in 
     ordinary everyday experience into the realm which is difficult to conceptualize because there is no 
     analog of the quantum world in our everyday experience.  One of the basic tenets of quantum mechanics 
     is that the deterministic nature we had grown accustomed to is lost; everything at the quantum level is 
     inherently probabilistic.  Nothing can be determined with absolute certainty, only to within limits given 
     by the Heisenberg uncertainty principle.  This represents a radical departure from what has been heretofore 
     learned, and arguably much of the difficulty of learning quantum mechanics is realizing and accepting this 
     adjustment.  But the theoretical consistency of quantum mechanics with experimental results are undeniable.  
     Though seemingly bizarre and awkward, quantum mechanics simply works.  
     </q></p></h2>
  </body>    
  <br>
  <ul><u>Quantum Mechanics Links</u>
  <li><a href=http://www.livescience.com/33816-quantum-mechanics-explanation.html>Live Science: What is Quantum Mechanics</li>
  <li><a href=http://www.qubit.it/links/quantumlist.html>QUBit Quantum Mechanics Links</li>
  </ul>
</html>

app/views/science/shome.html.erb
<html>
  <body>
     <div class="center jumbotron">
         <h1><b>SCIENCE</b></h1>
     </div>
     <div>
     <h2><p>This is the science home page.  Below are links to pages with information about
     some of the exciting fields of scientific studies.  </p></h2>
       <ul>
           <li><%= link_to "General Physics", generalphysics_path %></li>
           <li><%= link_to "Astronomy", astronomy_path %></li>
           <li><%= link_to "Electromagnetism" , electromagnetism_path %></li>
           <li><%= link_to "Mechanics, Dynamics, Largangian, Hamiltionain", mechanicsdynamicslagrangianhamiltonian_path %></li>
           <li><%= link_to "Quantum Mechanics", quantummechanics_path %></li>
           <li><%= link_to "Thermodynamics and Statistical Mechanics", thermodynamicsstatisticalmechanics_path %></li>
           <li><%= link_to "Nuclear and Particle Physics", nuclearparticlephysics_path %></li>
           <li><%= link_to "Astrophysics", astrophysics_path %></li>
           <li><%= link_to "Relativity", relativity_path %></li>
           <li><%= link_to "Fluid Dynamics", fluiddynamics_path %></li>
       </ul>
       </div>
  </body>    
</html>